_BASE_: [
  '../datasets/publaynet_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/cascade_rcnn_r50_fpn.yml',
  '_base_/cascade_fpn_reader.yml',
]

V2Net:
  layers: 50
  out_channels: 128

epoch: 8
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [3, 6]
  - !LinearWarmup
    start_factor: 0.1
    steps: 500
