_BASE_: [
  '../datasets/publaynet_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/cascade_rcnn_r50_fpn.yml',
  '_base_/cascade_fpn_reader.yml',
]

ResNet:
  layers: 101
  in_channels: [256, 512, 1024, 2048]
  out_channels: 768
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4
  lr_mult_list: [0.05, 0.05, 0.1, 0.15]

epoch: 8
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [3, 6]
  - !LinearWarmup
    start_factor: 0.1
    steps: 500
